version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: book_store
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    image: book-store
    container_name: spring_app
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/book_store
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: haveAGoodDayIfYouReadIt243509349584398534025
      JWT_EXPIRATION: 3000000000000
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - db

volumes:
  mysql_data: