version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQLDB_ROOT_PASSWORD: 1234567
      MYSQLDB_DATABASE: book_store
      MYSQLDB_USER: root
      MYSQLDB_PASSWORD: 1234567
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: