version: "3.8"

services:
  mysqldb:
    platform: linux/amd64
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQLDB_ROOT_PASSWORD=1234567
      - MYSQLDB_DATABASE=book_store
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: book-store
    build: .
    env_file: ./.env
    ports:
      - 8081:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:3306/book_store",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "1234567",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.H2Dialect"
      }'
