version: "3.8"
services:
  mysqldb:
    platform: linux/amd64
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=1234567
      - MYSQL_DATABASE=book-store
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 30s
      retries: 3
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    image: book-store
    build: .
    env_file: ./.env
    ports:
      - 8088:8080
      - 5005:5005
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/book-store",
      "spring.datasource.username" : "root",
      "spring.datasource.password" : "1234567",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
      "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
      "spring.jpa.hibernate.ddl-auto" : "update",
      "jwt.expiration": "1800000",
      "jwt.secret": "haveAGoodDayIfYouReadIt243509349584398534025"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
