version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQLDB_ROOT_PASSWORD: 1234567
      MYSQLDB_DATABASE: book_store
      MYSQLDB_USER: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    image: book-store
    container_name: spring_app
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:3307/book_store",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "1234567",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "jwt.secret" : "haveAGoodDayIfYouReadIt243509349584398534025",
        "jwt.expiration" : "3000000000000"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - db

volumes:
  mysql_data:
